

const ADD_COUNTER = "ADD_COUNTER";
const REDUCE_COUNTER = "REDUCE_COUNTER";
const MULTIPLY_COUNTER = "MULTIPLY_COUNTER"
const DIVIDE_COUNTER = "DIVIDE_COUNTER"
const ADD_TODOS = "ADD_TODOS";
const TOGGLE_TODOS = "TOGGLE_TODOS";
const DELETE_TODOS = "DELETE_TODOS";
const EDIT_TODOS = "EDIT_TODOS";

export {
    ADD_COUNTER,
    REDUCE_COUNTER,
    MULTIPLY_COUNTER,
    DIVIDE_COUNTER,
    ADD_TODOS,
    TOGGLE_TODOS,
    DELETE_TODOS,
    EDIT_TODOS,
};
